---
ingress:
  - hostname: "trentscholl.com"
    service: https://nginx-external-controller.network.svc.cluster.local:443
    originRequest:
      originServerName: ingress-ext.trentscholl.com
  - hostname: "*.trentscholl.com"
    service: https://nginx-external-controller.network.svc.cluster.local:443
    originRequest:
      originServerName: ingress-ext.trentscholl.com
  - service: http_status:404